DEBUG=True
CAMERA=True
FIRST_CAMERA="rtsp://admin:Admin123@192.168.1.64:554/Streaming/channels/1/"

FIRST_CAMERA_IP="http://192.168.1.64"
FIRST_CAMERA_USER_NAME="admin"
FIRST_CAMERA_USER_PASS="Admin123"

SECOND_CAMERA="http://admin:@192.168.1.101/cgi-bin/net_video.cgi?channel=1"

# API Details
API="http://localhost:62850/Account/LginStatus"

Plaza_GID="PLAZA001"
Lane_GID="LANE001"

MS_DATABASE_HOST="localhost"
MS_DATABASE_PORT=3306
MS_DATABASE_USER="shubham"
MS_DATABASE_PASSWORD="dubey"
MS_DATABASE_NAME="TMS_Client"

SERVER_MS_DATABASE_HOST="172.16.1.11"
SERVER_MS_DATABASE_PORT=3306
SERVER_MS_DATABASE_USER="sa"
SERVER_MS_DATABASE_PASSWORD="vikram@apl123"
SERVER_MS_DATABASE_NAME="Toll_Server"
